version: '{build}'
skip_tags: true
image: Visual Studio 2019
test: off
build_script:
- ps: ./Build.ps1
artifacts:
- path: artifacts/Serilog.Sinks.BrowserHttp.*.nupkg;artifacts/Serilog.AspNetCore.Ingestion.*.nupkg
deploy:
- provider: NuGet
  skip_symbols: true
  api_key:
    secure: GHDQ/obUdI88T5nch7dTrsESsQ/sGXPZUXt2F2rwAwo2e7YT6Svm5XBaFEmmMJAj
  on:
    branch: /^(main|dev)$/

